version: "1"

services:
  web:
    build: .
    ports:
      - 8000:8000
  postgres:
    image: postgres:alpine
    container_name: postgres
#    environment:
#      POSTGRES_DB: sparkdb
#      POSTGRES_USER: talha
#      POSTGRES_PASSWORD: mypass
    volumes:
      - sqldb:/var/lib/postgresql/data
    ports:
      - "9029:5432"